plugins:
  - jekyll-remote-theme
remote_theme: mimneko/Kiss-Jekyll-Lite@v1.0.0

baseurl: "/sample-page"
url: "https://mimneko.github.io" # サイトのURL。
customs: 
  - '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css">'
  - '<script src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js"></script>'
  - '<script src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/auto-render.min.js"></script>'
  - '<script>document.addEventListener("DOMContentLoaded", function() {renderMathInElement(document.body, {delimiters: [{left: "$$", right: "$$", display: true},{left: "$", right: "$", display: false},{left: "\\[", right: "\\]", display: true},{left: "\\(", right: "\\)", display: false}]});});</script>'
