plugins:
  - jekyll-remote-theme
remote_theme: mimneko/Kiss-Jekyll-Lite@v1.2.0

baseurl: "/sample-page"
url: "https://mimneko.github.io" # サイトのURL。
customs: 
#  - '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css">'
#  - '<script src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js"></script>'
#  - '<script src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/auto-render.min.js"></script>'
#  - '<script>document.addEventListener("DOMContentLoaded", function() {renderMathInElement(document.body, {delimiters: [{left: "$$", right: "$$", display: true},{left: "$", right: "$", display: false},{left: "\\[", right: "\\]", display: true},{left: "\\(", right: "\\)", display: false}]});});</script>'
  - '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer">'
  - '<script>MathJax = {tex: {inlineMath: [['$', '$'], ['\\(', '\\)']]}};</script>'
  - '<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>'
